[build]
  command = "yarn install --frozen-lockfile && yarn generate-json && yarn build"
  publish = "dist"

[build.environment]
NODE_VERSION = "20"
NODE_ENV = "production"
YARN_FLAGS = "--frozen-lockfile"
NETLIFY_USE_YARN = "true"

[build.processing]
  skip_processing = false

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"